<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" 
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    name="wheelchair_iaslab">

    <xacro:arg name="prefix" default="wcias_"/>
    
    <xacro:include filename="$(find wheelchair_iaslab_description)/urdf/wheelchair_iaslab.gazebo"/> 

    <xacro:property name="M_PI" value="3.1415926535897931"/>

    <!-- Base Properties: width = y axis, length = x axis, z = height axis -->
   <!--- <xacro:property name="base_width" value="0.47" /> --> <!--From right wheel to left wheel-->
    <!--<xacro:property name="base_length" value="0.88"/> --> <!--88 - 23 = 65--> <!--From front wheel to back wheel-->
  <!--- <xacro:property name="base_height" value="0.44"/> --> <!--From lower base to upper base of chair--> 
    
     <xacro:property name="base_width" value="0.475" /> <!--From the centre of the right wheel to the centre of the left wheel-->
     <xacro:property name="base_length" value="0.8275"/> <!-- From the centre of small wheel to the main wheel (included the diameter)-->
     <xacro:property name="base_height" value="0.44" /> <!-- From the ground to before pillow-->
     <xacro:property name="base_mass" value="10.0" /> <!--in Kg-->
     
    <!-- Chair back properties -->
    <xacro:property name="chair_back_width" value="0.43" />
    <xacro:property name="chair_back_length" value="0.23" />
    <xacro:property name="chair_back_height" value="0.82" />
    <xacro:property name="chair_back_mass" value="1.0" />

    <!-- Pillow properties -->
    <xacro:property name="pillow_width" value="0.42" />
    <xacro:property name="pillow_length" value="0.485" />
    <xacro:property name="pillow_height" value="0.07" />


    <!-- Legs properties -->
    <xacro:property name="legs_width" value="0.43" />
    <xacro:property name="legs_length" value="0.25" />
    <xacro:property name="legs_height" value="0.30" /> <!--about, to be remeasured-->
    <xacro:property name="legs_mass" value="2.0" />

    <!-- Wheels Properties -->
    <!-- Front wheel properties-->
    <xacro:property name="main_wheel_length" value="0.04" />
    <xacro:property name="main_wheel_radius" value="0.17" />
    <xacro:property name="main_wheel_mass" value="2.0" />

    <!-- Rear wheel properties -->
    <xacro:property name="small_wheel_length" value="0.035" />
    <xacro:property name="small_wheel_radius" value="0.10" />
    <xacro:property name="small_wheel_mass" value="1.0" />


    <!-- Inertia matrices -->
    <!--Maybe swap w and l-->
    <xacro:macro name="box_inertia" params="w l h m" >
        <inertia ixx="${1/12*m*(l*l+h*h)}" ixy="0" ixz="0"
                 iyy="${1/12*m*(w*w+l*l)}" iyz="0"
                 izz="${1/12*m*(w*w+h*h)}" />
    </xacro:macro>

    <!--m = mass, r = radius, h = height -->
    <xacro:macro name="cylinder_inertia" params="m r h" >
        <inertia ixx="${1/12*m*(3*r*r + h*h)}" ixy="0" ixz="0"
                 iyy="${1/12*m*(3*r*r + h*h)}" iyz="0" 
                 izz="${1/2*m*r*r}" />
    </xacro:macro>


    <!-- Links and joints definitions -->
    
    <!-- Footprint and base -->
    <link name="$(arg prefix)base_footprint" />

    <joint name="$(arg prefix)base_footprint_joint" type="fixed">
        <parent link="$(arg prefix)base_footprint" />
        <child link="$(arg prefix)base_link" />
        <origin xyz="0.0 0.0 ${base_height/2 + main_wheel_radius}" rpy="0 0 0" />
    </joint>

    <link name="$(arg prefix)base_link">
        <inertial>
            <!--origin?-->
            <mass value="${base_mass}" />
            <xacro:box_inertia w="${base_width}" l="${base_length}" h="${base_height}" m="${base_mass}" />
        </inertial>
        
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <!--origin?-->
            <material name="black">
                <color rgba="0 0 0 0.4"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <!--origin?-->
        </collision>
    </link>


    <!-- Chair back -->
    <link name="$(arg prefix)chair_back_link" >
        <!--inertial?-->
        <visual>
            <!--origin?-->
            <geometry>
                <box size="${chair_back_length} ${chair_back_width} ${chair_back_height}" />
            </geometry>
            <material name="black">
                <color rgba="1 1 1 0.4" />
            </material>
        </visual>

        <collision>
            <!--origin?-->
            <geometry>
                <box size="${chair_back_length} ${chair_back_width} ${chair_back_height}" />
            </geometry>
        </collision>
    </link>

    <joint name="$(arg prefix)chair_back_joint" type="fixed" >
        <parent link="$(arg prefix)base_link" />
        <child link="$(arg prefix)chair_back_link" />
        <origin xyz="-${base_length/2 - 0.35} 0 ${base_height/2 + chair_back_height/2}" rpy="0 0 0" />
    </joint>


    <!-- Legs -->
    <link name="$(arg prefix)legs_link">
        <inertial>
            <!--Origin?-->
            <mass value="${legs_mass}"/>
            <xacro:box_inertia w="${legs_width}" l="${legs_length}" h="${legs_height}" m="${legs_mass}" />
        </inertial>

        <visual>
            <geometry>
                <box size="${legs_length} ${legs_width} ${legs_height}" />
            </geometry>
            <!--origin?-->
            <material name="black">
                <color rgba="0 0 0 0.4" />
            </material>
        </visual>

        <collision>
            <!--origin?-->
            <geometry>
                <box size="${legs_length} ${legs_width} ${legs_height}" />
            </geometry>
        </collision>
    </link>

    <joint name="$(arg prefix)legs_joint" type="fixed">
        <parent link="$(arg prefix)base_link" />
        <child link="$(arg prefix)legs_link" />
        <origin xyz="${base_length/2 + legs_length/2} 0 -${base_height/2 - legs_height/2 + 0.07}" rpy="0 0 0" />
    </joint>


    <!-- Front wheels -->
    <link name="$(arg prefix)left_main_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <mass value="${main_wheel_mass}" />
            <xacro:cylinder_inertia m="${main_wheel_mass}" r="${main_wheel_radius}" h="${main_wheel_length}" />
        </inertial>
        
        <visual>
            <geometry>
                <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <material name="black">
                <color rgba="0 0 0 0.4"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        </collision>
    </link>

    <joint name="$(arg prefix)left_main_wheel_joint" type="continuous" >
        <parent link="$(arg prefix)base_link" />
        <child link="$(arg prefix)left_main_wheel_link" />
        <origin xyz="0.23  ${base_width/2 + main_wheel_length/2} -${base_height/2}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <joint_properties damping="0.0" friction="0.0" />
    </joint>

    <link name="$(arg prefix)right_main_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <mass value="${main_wheel_mass}" />
            <xacro:cylinder_inertia m="${main_wheel_mass}" r="${main_wheel_radius}" h="${main_wheel_length}" />
        </inertial>
        
        <visual>
            <geometry>
                <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <material name="black">
                <color rgba="0 0 0 0.4"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        </collision>
    </link>

    <joint name="$(arg prefix)right_main_wheel_joint" type="continuous" >
        <parent link="$(arg prefix)base_link" />
        <child link="$(arg prefix)right_main_wheel_link" />
        <origin xyz="0.23  -${base_width/2 + main_wheel_length/2} -${base_height/2}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <joint_properties damping="0.0" friction="0.0" />
    </joint>

    <!-- Rear wheels -->
    <link name="$(arg prefix)left_small_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <mass value="${small_wheel_mass}" />
            <xacro:cylinder_inertia m="${small_wheel_mass}" r="${small_wheel_radius}" h="${small_wheel_length}" />
        </inertial>
        
        <visual>
            <geometry>
                <cylinder length="${small_wheel_length}" radius="${small_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <material name="black">
                <color rgba="0 0 0 0.4"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${small_wheel_length}" radius="${small_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        </collision>
    </link>

    <joint name="$(arg prefix)left_small_wheel_joint" type="continuous" >
        <parent link="$(arg prefix)base_link" />
        <child link="$(arg prefix)left_small_wheel_link" />
        <origin xyz="-${base_length/2}  ${base_width/2 + small_wheel_length/2} -${base_height/2 + 0.07}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <joint_properties damping="0.0" friction="0.0" />
    </joint>

    <link name="$(arg prefix)right_small_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <mass value="${small_wheel_mass}" />
            <xacro:cylinder_inertia m="${small_wheel_mass}" r="${small_wheel_radius}" h="${small_wheel_length}" />
        </inertial>
        
        <visual>
            <geometry>
                <cylinder length="${small_wheel_length}" radius="${small_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <material name="black">
                <color rgba="0 0 0 0.4"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${small_wheel_length}" radius="${small_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        </collision>
    </link>

    <joint name="$(arg prefix)right_small_wheel_joint" type="continuous" >
        <parent link="$(arg prefix)base_link" />
        <child link="$(arg prefix)right_small_wheel_link" />
        <origin xyz="-${base_length/2}  -${base_width/2 + small_wheel_length/2} -${base_height/2 + 0.07}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <joint_properties damping="0.0" friction="0.0" />
    </joint>
    <!--The 0.07cm is the difference between the radius of the two wheels-->

  

</robot>

