<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" 
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    name="wheelchair_iaslab_sensors">

<xacro:include filename="wheelchair_iaslab.xacro" />  

<!-- Laser Hokuyo properties -->
<xacro:property name="laser_length" value="0.04" />
<xacro:property name="laser_radius" value="0.035" />
<xacro:property name="laser_mass" value="0.160" />


  <!-- Laser Hokuyo-->
    <link name="$(arg prefix)hokuyo_laser_link_left" >
        <visual>
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}"/>
            </geometry>
            <material name="red">
                <color rgba="255 0 0 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${laser_mass}" />
            <xacro:cylinder_inertia m="${laser_mass}" r="${laser_radius}" h="${laser_length}" />
        </inertial>
    </link>

    <joint name="$(arg prefix)base_laser_joint_left" type="fixed">
        <!--<parent link="$(arg prefix)base_link"/>
        <child link="$(arg prefix)hokuyo_laser_link_left"/>
        <origin xyz="${pillow_length/2 + 0.105} 0.295 ${base_height/2 + pillow_height - 0.035}" rpy="0 0 0" /> -->
        <axis xyz="0 1 0"/>
<parent link="$(arg prefix)base_footprint"/>
        <child link="$(arg prefix)hokuyo_laser_link_left"/>
        <!-- <origin xyz="0.346609  0.295568  0.645" rpy="0 0 0" /> -->
         <origin xyz="0.346609  0.0  0.645" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>
    
   

    <link name="$(arg prefix)hokuyo_laser_link_right" >
        <visual>
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}"/>
            </geometry>
            <material name="red">
                <color rgba="255 0 0 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${laser_mass}" />
            <xacro:cylinder_inertia m="${laser_mass}" r="${laser_radius}" h="${laser_length}" />
        </inertial>
    </link>

    <joint name="$(arg prefix)base_laser_joint_right" type="fixed">
       <!-- <parent link="$(arg prefix)base_link"/>
        <child link="$(arg prefix)hokuyo_laser_link_right"/>
        <origin xyz="${pillow_length/2 + 0.11}  -0.295 ${base_height/2 + pillow_height - 0.02}" rpy="0 0 0" /> 
        <axis xyz="0 1 0"/>-->
<parent link="$(arg prefix)base_footprint"/>
        <child link="$(arg prefix)hokuyo_laser_link_right"/>
        <origin xyz="0.346609  -0.295568  0.66" rpy="0 0 0" /> 
        <axis xyz="0 1 0"/>-->

    </joint>


<!-- Real sense stereo camera-->

<xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />

<xacro:sensor_d435 name="stereo_camera" parent="$(arg prefix)base_footprint" >
<origin xyz=" 0.308867 0.24485 0.8" rpy="0 0 0" />
    <!--<origin xyz="${pillow_length/2 +0.04}  0.277 ${base_height/2 + pillow_height + 0.12}" rpy="0 0 0" />-->
  </xacro:sensor_d435> 



<!-- Real sense LIDAR camera-->

<xacro:include filename="$(find realsense2_description)/urdf/_l515.urdf.xacro" />

<xacro:sensor_l515 name="lidar_camera" parent="$(arg prefix)base_footprint" >
<origin xyz="0.302795 -0.0503142 0.705" rpy="0 0 0" />
    <!--<origin xyz="${pillow_length/2 +0.115}  0 ${base_height/2 + pillow_height + 0.025}" rpy="0 0 0" />-->
  </xacro:sensor_l515> 



</robot>




